### ISSUE TITLE
Add plugin sandbox

### ISSUE THREAD

**Issue by kangax** [thejameskyle/babel-plugin-handbook#12]
...where you can quickly experiment with a plugin, provide input and see output.

Currently you have to `npm install babel-core`, create separate (most likely) plugin file and a test file with some input, then run it.

**Comment by thejameskyle** [comment]
You mean like http://felix-kling.de/esprima_ast_explorer/

**Comment by faceyspacey** [comment]
wow that would be awesome +1

**Comment by kangax** [comment]
Hey @thejameskyle, sorry for the delay, your reply somehow slipped through the cracks.

Yes, Felix' explorer is helpful but not exactly what I had in mind. The explorer translates code (column 1) to AST (column 2) whereas plugin sandbox would transform code (column 1) and plugin (column 2) into another code (column 3).

Even more ideal would probably be to combine AST explorer with sandbox (or the other way around), meaning that you could paste input code, see its AST, write plugin with the help of that AST, and finally see output according to a plugin.

         |------> [ AST ]
    [ input ] --> [ babel plugin ] -> [ output ]

AST itself is not entirely helpful since you still need to write babel-specific DSL on top of it.

Does that make sense?

**Comment by fkling** [comment]
@kangax: astexplorer lets you write Babel plugins, if you select babel or babelv6 under "Transform". It seems to me that this would fit your expectations, but maybe I'm wrong.

Either way, I'm happy to explore options to make astexplorer more useful for Babel plugin development, one way or the other!

**Comment by thejameskyle** [comment]
Yeah, astexplorer already has a ton of features to it, I'd rather see that project grow and get more contributors than try replicating part of the functionality

**Comment by kangax** [comment]
Oh... yes, this is perfect. I missed the transform option on ASTExplorer! Thanks :)
