### ISSUE TITLE
Is there any way to define the relations of other plugins?

### ISSUE THREAD

**Issue by hax** [thejameskyle/babel-plugin-handbook#17]
For example, 
- Exclusive: https://github.com/hax/babel-plugin-transform-es2015-generator-return should not be used with `transform-regenerator`.
- Order: `transform-async-to-generator` should prior to `transform-es2015-parameters` (see babel bug: https://phabricator.babeljs.io/T2776)

Currently I found `pluginStack` in  `visitors: { XXX(path, state) { state.file.pluginStack } }`, so I could check the plugins and throw error in runtime, but that seems too hacky.

**Comment by thejameskyle** [comment]
Plugins shouldn't know about each other at all so no there is not.

**Comment by hax** [comment]
@thejameskyle 
But my examples give the use cases which they should know...
Maybe I should ask for the feature in https://phabricator.babeljs.io/ ?

**Comment by thejameskyle** [comment]
- https://phabricator.babeljs.io/T2776 needs to be fixed
- You should document https://github.com/hax/babel-plugin-transform-es2015-generator-return

> Maybe I should ask for the feature in https://phabricator.babeljs.io/ ?

It will almost certainly be rejected

**Comment by hax** [comment]
> Plugins shouldn't know about each other at all

@thejameskyle I found that many plugins depend on other plugin by `inherits` it (for examples, [transform-async-functions](https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-async-functions/src/index.js) and `transform-es2015-modules-*`).
Inheritance is a very strong relationship, so I don't think your proposition "should not know about each other" accord to current codes.
If inheritance is allowed, why not support other relationships?

**Comment by thejameskyle** [comment]
Inheritance is not even comparable to two entirely separate plugins having knowledge about the order of which they are run. So no that is not justification of supporting any kind of relationship as you describe.

**Comment by hax** [comment]
@thejameskyle  The problem here is that how to define one plugin is NOT "entirely separate" with other. Inheritance is a special case which the original author of a plugin can define when he/she design/develop it for the sake of reuse implementation. What I argue is there are valid use cases for other relations. For example, my first case `transform-es2015-generator-return` vs `regenerator`, I don't think document is enough.

**Comment by thejameskyle** [comment]
The vast majority of the time when people want a particular order for their plugins, they have done something incorrectly. The other tiny percentage of the time documentation is good enough.

Even if we wanted to, there is absolutely no way of being able to tell the order of plugins. By the time they get into Babel's pipeline they have to be resolved to just plain functions. They don't have ids, they don't have names of any sort, nor should they. What you are suggesting just isn't going to ever happen.

**Comment by hax** [comment]
@thejameskyle I have a case which require control the order of the plugins.

One plugin will wrap function expression like that:
````js
var x = function () {}
``` => ```js
var x = _wrap(function () {})
```
On the other hand `transform-es2015-function-name` will do:
````js
var x = function () {}
``` => ```js
var x = function x() {}
```
If wrap transformation run first, then `transform-es2015-function-name` will fail.

My current workaround is move wrapping to exit phase, and require wrap transformer written before `transform-es2015-function-name` in options. But it's awful. Oh maybe you can teach me where I "have done something incorrectly."
