### ISSUE TITLE
Source Pre-Processing

### ISSUE THREAD

**Issue by KenPowers** [thejameskyle/babel-plugin-handbook#19]
Is it possible to pre-process source code using a Babel plugin? For example, say I liked the idea behind [literate coffeescript](http://coffeescript.org/#literate) and I wanted to apply that to JavaScript as a Babel plugin (thus creating literate JavaScript). [CoffeeScript appears to accomplish this by commenting out markdown lines before running the code through the compiler.](https://github.com/jashkenas/coffeescript/blob/b8403bfa97e8aa662781af30d38a8c953119ab12/src/helpers.coffee#L70-L82)

**Comment by thejameskyle** [comment]
No, you can't do this as a Babel plugin, by the time plugins run the file has already been parsed.

**Comment by KenPowers** [comment]
What would be your recommendation? It would be cool if Babel could support pre-processing.

**Comment by thejameskyle** [comment]
Pass the preprocessed code to Babel somehow

**Comment by KenPowers** [comment]
Key word *somehow*. :smile:

**Comment by thejameskyle** [comment]
Heh, you can pass transformed code to `babel.transform` however you want
