### ISSUE TITLE
would it be possible to parse Handlebars and generate JSX using a Babel plugin?

### ISSUE THREAD

**Issue by faceyspacey** [thejameskyle/babel-plugin-handbook#21]
I'm looking to parse Handlebars into JSX. There are no solutions currently out. Would a babel-plugin be able to parse Handlebars style HTML, or can it only address javascript? What would the recommended way to do this be?

**Comment by thejameskyle** [comment]
You can compile Handlebars into JavaScript and then hand it off, but it's not possible to parse an entirely new syntax via babel plugins. You probably wouldn't want to either.
