### ISSUE TITLE
How do we "load" these plugins in conjunction with presets?

### ISSUE THREAD

**Issue by Pomax** [thejameskyle/babel-plugin-handbook#31]
Great reference! But I'm missing a section that explains how to use "your own plugin" in a `.babelrc` file. Obviously there's the `plugins` section, but what if -like most setups- you use the es2015 and react presets? How does one load their own plugin so that it executes before the presets are used, for instance? (or in between, or after, for that matter?)

**Comment by thejameskyle** [comment]
There isn't really an "order" since all the visitors just get merged as one. Also 99% of the time when you think the order matters you're probably being way too specific with your transform.

**Comment by Pomax** [comment]
sometimes specific is necessary: I had to make sure LaTeX code got rewritten to a safe form "first", before es2015 and react-jsx kicked, so that things wouldn't die on the multitude of `\` and `{`/`}`. I ended up writing that preprocessing as a webpack loader instead, so that it kicked in before babel itself did its thing with the es2015 and react presets, and that worked quite well (although webpack just gives you "source" which isn't quite as nice as an AST)
