### ISSUE TITLE
Question: How to deal with html tags when modifying StringLiterals?

### ISSUE THREAD

**Issue by inakianduaga** [thejameskyle/babel-plugin-handbook#33]
Disclaimer: Using this guide to write my first babel plugin so bear with me if this is some stupid mistake. 

I don't know what's wrong with a visitor that updates StringLiterals.

[this example](http://astexplorer.net/#/qr8Tldx6c6) is working as expected on astexplorer.net. 

However, when running the same example inside an [npm package I'm writing](https://github.com/inakianduaga/babel-plugin-markdown-compiler/blob/develop/src/index.js#L8), I get the following error:

```
Error: Cannot find module '<p>Some html tag</p>'
    at Function.Module._resolveFilename (module.js:337:15)
```

The command I'm using to run the test is 

```sh 
BABEL_DISABLE_CACHE=1 BABEL_ENV=testing ./node_modules/mocha/bin/mocha --compilers js:babel-register test/index.js
```

and `.babelrc` is referencing the local repo to run the test

```json
{
  "presets": ["es2015"],
  "env": {
    "testing": {
      "plugins": ["./src"]
    }
  }
}
```

By the way, unrelated but I spent a few minutes at a loss because of the `BABEL_DISABLE_CACHE` option which seems to be required otherwise `babel-require` caches the code by default and some stuff suddenly stopped updating. Perhaps it should be documented somewhere.

**Comment by thejameskyle** [comment]
You must be doing:

```js
import foo from 'foo';
```

**Comment by thejameskyle** [comment]
You must be doing:

```js
import foo from 'foo';
```

somewhere which your plugin is transforming to:

```js
import foo from '<p>Some html tag</p>';
```

**Comment by inakianduaga** [comment]
@thejameskyle God you're right, the plugin is being applied to its own file, so obviously it fails. Thanks a bunch!

**Comment by thejameskyle** [comment]
> God you're right, the plugin is being applied to its own file, so obviously it fails.

What? How?

**Comment by inakianduaga** [comment]
The way I setup the tests is I run mocha with the `--compilers` flag to include babel, and I add the plugin that I'm building as a `.babelrc` plugin. So the plugin runs over not only the test files, as I wanted, but over the index.js plugin code itself, breaking it since the plugin right now is very dumb and replaces all string literals.

**Comment by thejameskyle** [comment]
But... it's not possible for the plugin to run on itself before it is compiled, it's a circular dependency. This is confusing

**Comment by inakianduaga** [comment]
@thejameskyle Yeah, you're right about that, the plugin itself is not getting rewritten, but this file

https://github.com/inakianduaga/babel-plugin-markdown-compiler/blob/develop/test/index.js

(the test file one that imports the fixture/expectations), is, and it has 2 imports on top which are getting rewritten and cause the error.

By the way, do you know of a way to restrict a babel plugin from applying to only certain things? For example, if I would be dealing with classes I could add the notation `@markdown` to the class to indicate that I want to apply the plugin to this class. However, I can't do that for regular objects. And comments don't seem to show up in the AST. So I'm not seeing an easy way to restrict the plugin to apply to only certain parts of the codebase.

**Comment by thejameskyle** [comment]
I wouldn't recommend using comments to designate when plugins should run, that is a recipe for disaster
