### ISSUE TITLE
Are there any file/folder naming and structure conventions to writing a babel plugin?

### ISSUE THREAD

**Issue by onlywei** [thejameskyle/babel-plugin-handbook#36]
In the blog post http://shuheikagawa.com/blog/2015/09/13/lets-create-a-babel-plugin/, it spoke of using the `babel-plugin` cli to create a skeleton shell project for your babel plugin. Now, this CLI is no longer available. Am I still supposed to follow the filenames and directory structures that are described there?

**Comment by thejameskyle** [comment]
Yeah the normal file structure is still the same, heres a good example: https://github.com/thejameskyle/babel-plugin-react-pure-components

**Comment by onlywei** [comment]
In that example, in the `package.json` file it still has:

```
  "scripts": {
    "build": "babel-plugin build",
    "push": "babel-plugin publish",
    "test": "mocha --compilers js:babel-register"
  },
```

Wouldn't those `babel-plugin` commands stop working if Babel 6 is installed globally?

**Comment by thejameskyle** [comment]
Oh weird, well those just translate to:

```sh
$ babel src --out-dir lib --copy-files
```

and

```sh
$ git pull
$ git push
$ babel src --out-dir lib --copy-files
$ npm version [version]
$ npm publish
$ git push --follow-tags
```
