### ISSUE TITLE
Document path.hub.file.addImport

### ISSUE THREAD

**Issue by gajus** [thejameskyle/babel-plugin-handbook#37]
I cannot find documentation describing behaviour of the `path.hub.file.addImport` method.

I have only found this, https://github.com/babel/babel/blob/0749e2dd92ab40f64db9329db94bd16421c70bb1/packages/babel-core/src/transformation/file/index.js#L235-L260.

**Comment by thejameskyle** [comment]
Real API documentation should be coming in the near future https://github.com/babel/babel/pull/3114
