### ISSUE TITLE
Possible to pass options through CLI?

### ISSUE THREAD

**Issue by CrocoDillon** [thejameskyle/babel-plugin-handbook#41]
Doing something like this:

```bash
babel src --out-dir lib --plugins myplugin
```

Is it possible to make that plugin accept options from the CLI?

**Comment by thejameskyle** [comment]
Please take support queries to the Babel Slack https://slack.babeljs.io/

**Comment by CrocoDillon** [comment]
Okay.

I asked here because I guess this is where people come if they want to create a plugin. _If_ it is possible to pass options using `babel-cli` it would be nice if there was an example of that under [Plugin Options](https://github.com/thejameskyle/babel-plugin-handbook#plugin-options).

Current example does not cover any of that. Not saying it's not possible but also not saying it is.

Thanks for your reply though! Appreciate it.
