### ISSUE TITLE
preprocessing plugin?

### ISSUE THREAD

**Issue by Pomax** [thejameskyle/babel-plugin-handbook#45]
I can't seem to find anything in the plugin handbook about writing plugins that kicks in *before* the AST gets built, so that "nearly legal" syntax (for instance, JSX with LaTeX code in it, which will break a compile attempt) can be converted to legal syntax before Babel tries to build the AST off of it.

I [asked this over on stackoverflow](http://stackoverflow.com/questions/34844699/how-to-bind-a-preprocessor-to-babel-register-to-modify-files-before-babel-kicks) as well, as that's one of the official Babel.io support channels, but the gist is that I'm using `babel-register` in Node.js to make sure ESnext and JSX files can be required as any other module, and this breaks because I can't tell babel that it needs to first run the file-as-string through a function that changes the AST-breaking bits to JSX-conformant bits so that Babel can do its thing.

**Comment by thejameskyle** [comment]
Thats not considered valid usage of Babel plugins. Preprocess on your own and pass the resulting string of code to Babel.

**Comment by Pomax** [comment]
Yeah that's kind of the problem. You can't "preprocess on your own" with `babel-register`, since it literally does magic that makes `require('whatever.jsx')` run through babel before binding the result for Node to use. Unless  you know of a way to hook into *that*, "preprocess on you own" is flat out impossible =(

**Comment by thejameskyle** [comment]
See https://github.com/babel/babel/pull/3139

**Comment by Pomax** [comment]
I've read through it, but I'm not quite sure which part you want me to get out of it? Do you recommend I write my own hook before babel-register, using `pirates`, similar to what this (failing) PR does?

**Comment by thejameskyle** [comment]
> Do you recommend I write my own hook before babel-register, using pirates

yes

**Comment by Pomax** [comment]
cool, thanks
