### ISSUE TITLE
Does has t.isX(y,{ z: w }) good enough performace?

### ISSUE THREAD

**Issue by Bobris** [thejameskyle/babel-plugin-handbook#7]
I am little bit concerned with this pattern:

    import traverse from "babel-traverse";
    import t from "babel-types";

    traverse(ast, {
       enter(path) {
         if (t.isIdentifier(path.node, { name: "n" })) {
           path.node.name = "x";
         }
      }
    });

It will allocate JS object for every test even if it is not Identifier. Babel will be used for huge programs and every such inefficiency will increase time for compilation. Is this really that worse?

         if (t.isIdentifier(path.node) && path.node.name==="n")

Or am I just so behind of V8 optimization capabilities?

**Comment by thejameskyle** [comment]
I wouldn't be concerned about that for performance, you would never notice a difference.

The biggest thing you should be concerned with is traversing the AST more than you need to. Babel has some really complex optimizations around this, but you should avoid it whenever possible.

One of the things that has a pretty hefty performance issue is allocating new visitors on each run. For example:

```js
traverse(ast, {
  FunctionDeclaration(path) {
    path.traverse({
      BinaryExpression(path) {
        // ...
      }
    })
  }
});
```

It is **far** better to do:

```js
const binaryExpressionVisitor = {
  BinaryExpression(path) {
    // ...
  }
};

traverse(ast, {
  FunctionDeclaration(path) {
    path.traverse(binaryExpressionVisitor)
  }
});
```

If you need to pass in state you can do:

```js
const binaryExpressionVisitor = {
  BinaryExpression(path) {
    console.log(this.stateProp); // "value"
    // ...
  }
};

traverse(ast, {
  FunctionDeclaration(path) {
    path.traverse(binaryExpressionVisitor, { stateProp: "value" })
  }
});
```

I should write a section about this under the Best Practices section.

**Comment by thejameskyle** [comment]
Moving my comments to https://github.com/thejameskyle/babel-plugin-handbook/pull/8
